import {platformProvider} from "/platform/ui/provider.js";
const surface=document.querySelector("#surface"),title=document.querySelector("#page-title");let current="student";document.querySelector("#session").textContent=platformProvider.mode==="real"?"اتصال به Core API":"نیاز به ورود";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function nav(view){document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view));}
function stat(label,value,note){return `<article class="card stat"><h3>${label}</h3><strong>${value}</strong><small>${note}</small></article>`}
function student(d){title.textContent="داشبورد دانش‌آموز";return `<div class="hero"><div><h2>سلام ${esc(d.name)}، آماده‌ای ادامه بدی؟</h2><p>امروز یک قدم کوچک، فردا یک پیشرفت بزرگ.</p><div class="actions" style="margin-top:18px"><button class="primary" data-view="tutor">شروع گفت‌وگو با دستیار</button><button class="secondary" data-view="assignment">مشاهده تکالیف</button></div></div><div class="hero-icon">🚀</div></div><div class="stats">${stat("پیشرفت هفتگی",d.progress+"٪","بر اساس داده‌های ثبت‌شده")}${stat("روزهای پیوسته",d.streak??"—","بر اساس داده‌های ثبت‌شده")}${stat("تکالیف فعال",d.assignments.length,"از سرویس واقعی")}${stat("امتیاز یادگیری","—","پس از ثبت داده نمایش داده می‌شود")}</div><div class="cards"><article class="card" style="padding:20px"><div class="section-head"><h2>تکالیف امروز</h2><button class="link" data-view="assignment">همه تکالیف</button></div><div class="list">${d.assignments.map(a=>`<div class="row ${a.status==='قفل‌شده'?'locked':''}"><div class="row-main"><span class="icon">${a.icon}</span><div><h3>${esc(a.title)}</h3><p>${esc(a.meta)}</p></div></div><span class="pill">${esc(a.status)}</span></div>`).join("")}</div></article><article class="card" style="padding:20px"><div class="section-head"><h2>مسیرهای یادگیری</h2><button class="link">جزئیات</button></div>${d.courses.map(c=>`<div style="margin:15px 0"><div class="section-head"><span>${esc(c.name)}</span><b>${c.value}٪</b></div><div class="progress"><i style="width:${c.value}%"></i></div></div>`).join("")}<div class="empty" style="margin-top:16px">پیشنهاد بعدی: مرور ۱۰ دقیقه‌ای فیزیک</div></article></div>`}
function teacher(d){title.textContent="داشبورد معلم";return `<div class="hero"><div><h2>پنل کلاس‌های شما</h2><p>${esc(d.name)} · مدیریت یادگیری با دید روشن</p><div class="actions" style="margin-top:18px"><button class="primary">ایجاد تکلیف</button><button class="secondary">گزارش عملکرد</button></div></div><div class="hero-icon">📚</div></div><div class="stats">${stat("کلاس‌ها",d.classes,"از سرویس واقعی")}${stat("دانش‌آموزان",d.students??"—","پس از اتصال داده کلاس نمایش داده می‌شود")}${stat("تحویل‌های جدید",d.submissions,"از سرویس واقعی")}${stat("کیفیت محتوا","—","پس از ثبت بازخورد نمایش داده می‌شود")}</div><article class="card" style="padding:20px"><div class="section-head"><h2>مرکز کارهای معلم</h2><button class="link">نمایش همه</button></div><div class="list">${d.items.map(a=>`<div class="row"><div><h3>${esc(a.title)}</h3><p>${esc(a.meta)}</p></div><span class="pill">${esc(a.status)}</span></div>`).join("")}</div></article>`}
async function simple(view){title.textContent=view==="tutor"?"دستیار هوشمند":view==="profile"?"پروفایل و اشتراک":"تکالیف";if(view==="tutor")return `<article class="card" style="padding:28px"><div class="section-head"><h2>دستیار هوشمند</h2><span class="pill">${platformProvider.mode==="real"?"Core API":"نیاز به ورود"}</span></div><form id="tutor-form"><label for="tutor-query">سؤال درسی شما</label><textarea id="tutor-query" required maxlength="10000" rows="5" placeholder="مثلاً قانون دوم نیوتن را توضیح بده"></textarea><button class="primary" type="submit">دریافت پاسخ</button></form><div id="tutor-result" class="empty" aria-live="polite">پاسخ با استناد به منابع آموزشی نمایش داده می‌شود.</div><div class="actions" style="margin-top:16px"><button class="secondary" data-view="student">بازگشت به داشبورد</button></div></article>`;if(view==="profile"){const d=await platformProvider.profile();const p=d.academic_profile||{};return `<article class="card" style="padding:28px"><div class="section-head"><h2>پروفایل و اشتراک</h2><span class="pill">${platformProvider.mode==="real"?"Core API":"نیاز به ورود"}</span></div><div class="list"><div class="row"><span>پایه</span><strong>${esc(p.grade||"ثبت نشده")}</strong></div><div class="row"><span>رشته</span><strong>${esc(p.field_of_study||"ثبت نشده")}</strong></div><div class="row"><span>پرسش‌های حل‌شده</span><strong>${d.stats?.total_solved_queries??0}</strong></div></div><div class="actions" style="margin-top:16px"><button class="primary" data-view="student">بازگشت</button></div></article>`}const d=await platformProvider.assignments();return `<article class="card" style="padding:28px"><div class="section-head"><h2>تکالیف</h2><span class="pill">${platformProvider.mode==="real"?"Core API":"نیاز به ورود"}</span></div>${(d.assignments||[]).length?`<div class="list">${d.assignments.map(a=>`<div class="row"><div><h3>${esc(a.title)}</h3><p>${esc(a.instructions||"تکلیف فعال")}</p></div><span class="pill">${esc(a.status||"فعال")}</span></div>`).join("")}</div>`:`<div class="empty">تکلیف فعالی وجود ندارد.</div>`}<div class="actions" style="margin-top:16px"><button class="primary" data-view="student">بازگشت</button></div></article>`}
async function load(view){current=view;nav(view);surface.innerHTML='<div class="loading">در حال بارگذاری سطح محصول…</div>';try{const d=await platformProvider.dashboard(view==="teacher"?"teacher":"student");document.querySelector("#session").textContent="اتصال به Core API";surface.innerHTML=view==="teacher"?teacher(d):view==="student"?student(d):await simple(view)}catch(e){surface.innerHTML=`<div class="error">${esc(e.message)}<br><button class="secondary" id="retry" style="margin-top:12px">تلاش دوباره</button></div>`}}
document.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)load(b.dataset.view);if(e.target.id==="retry")load(current)});
document.addEventListener("submit",async e=>{if(e.target.id!=="tutor-form")return;e.preventDefault();const result=document.querySelector("#tutor-result"),query=document.querySelector("#tutor-query").value.trim();if(!query)return;result.className="loading";result.textContent="در حال دریافت پاسخ…";try{const answer=await platformProvider.tutorAnswer(query,{language:"fa"});result.className="empty";result.textContent="";const text=document.createElement("p");text.textContent=answer.text||"پاسخ دریافت نشد.";result.appendChild(text);const citations=Array.isArray(answer.citations)?answer.citations:[];if(citations.length){const heading=document.createElement("strong");heading.textContent="منابع";result.appendChild(heading);const list=document.createElement("ul");citations.forEach(c=>{const item=document.createElement("li");item.textContent=[c.title,c.page?`صفحه ${c.page}`:"",c.source].filter(Boolean).join(" — ");list.appendChild(item)});result.appendChild(list)}}catch(err){result.className="error";result.textContent=err.message||"خطا در دریافت پاسخ."}});load("student");





