from enum import StrEnum


class SubscriptionPlan(StrEnum):
    FREE = "FREE"
    STUDENT_PLUS = "STUDENT_PLUS"
    STUDENT_PRO = "STUDENT_PRO"
    TEACHER_PRO = "TEACHER_PRO"
    SCHOOL = "SCHOOL"
    ENTERPRISE = "ENTERPRISE"


class FeatureCode(StrEnum):
    AI_CHAT = "AI_CHAT"
    BOOK_QA = "BOOK_QA"
    SMART_SUMMARY = "SMART_SUMMARY"
    FLASHCARDS = "FLASHCARDS"
    QUESTION_GENERATOR = "QUESTION_GENERATOR"
    EXAM_GENERATOR = "EXAM_GENERATOR"
    EXAM_CORRECTOR = "EXAM_CORRECTOR"
    PDF_EXPORT = "PDF_EXPORT"
    PODCAST_GENERATOR = "PODCAST_GENERATOR"
    STUDY_PLANNER = "STUDY_PLANNER"
    LEARNING_ANALYTICS = "LEARNING_ANALYTICS"
    ADAPTIVE_LEARNING = "ADAPTIVE_LEARNING"
    TEACHER_ASSISTANT = "TEACHER_ASSISTANT"
    SCHOOL_ANALYTICS = "SCHOOL_ANALYTICS"
    VOICE_TUTOR = "VOICE_TUTOR"

