(() => {"use strict";
const state={view:"overview",data:{}}; const $=s=>document.querySelector(s); const token=()=>sessionStorage.getItem("adminToken")||"";
const endpoints={schools:"/api/v1/admin/schools",users:"/api/v1/admin/users",content:"/api/v1/admin/content",usage:"/api/v1/admin/observability/overview",subscriptions:"/api/v1/admin/subscriptions",payments:"/api/v1/admin/payments"};
async function get(view){const r=await fetch(endpoints[view],{headers:token()?{Authorization:`Bearer ${token()}`}:{}}); if(!r.ok) throw new Error(r.status===401?"نشست احراز هویت منقضی شده است":r.status===403?"دسترسی مدیریت ندارید":"خطا در دریافت داده"); return r.json()}
function render(){const labels={overview:"نمای کلی",schools:"مدرسه‌ها",users:"کاربران",content:"محتوا",usage:"مصرف و مشاهده‌پذیری",subscriptions:"اشتراک‌ها",payments:"پرداخت‌ها"}; $("#title").textContent=labels[state.view]; document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view)); $("#session").textContent=token()?"توکن مدیریت موجود است":"نیاز به نشست مدیریت"; if(state.view==="overview"){const d=state.data; $("#cards").innerHTML=[...["schools","users","content"].map(k=>`<div class="card"><span>${labels[k]}</span><strong>${(d[k]?.items||[]).length}</strong></div>`),].join("");$("#table").innerHTML='<div class="empty">برای مشاهده جزئیات، یکی از بخش‌های کناری را انتخاب کنید.</div>'}else{$("#cards").innerHTML="";const items=state.data[state.view]?.items||[];$("#table").innerHTML=items.length?`<table><thead><tr>${Object.keys(items[0]).map(k=>`<th>${k}</th>`).join("")}</tr></thead><tbody>${items.map(x=>`<tr>${Object.values(x).map(v=>`<td>${String(v??"—").replace(/[<>]/g,"")}</td>`).join("")}</tr>`).join("")}</tbody></table>`:'<div class="empty">داده‌ای برای نمایش وجود ندارد.</div>'}}
async function load(view){state.view=view;$("#alerts").innerHTML='<div class="loading">در حال بارگذاری…</div>';try{if(view==="overview"){for(const k of ["schools","users","content"])state.data[k]=await get(k)}else state.data[view]=await get(view);$("#alerts").innerHTML="";render()}catch(e){$("#alerts").innerHTML=`<div class="error">${e.message}</div>`;$("#cards").innerHTML="";$("#table").innerHTML=""}}
document.querySelectorAll("nav button").forEach(b=>b.addEventListener("click",()=>load(b.dataset.view)));load("overview");
})();


