(()=>{"use strict";const $=s=>document.querySelector(s),state={items:[],selected:null};const token=()=>sessionStorage.getItem("studentToken")||"";const headers=()=>token()?{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"}:{"Content-Type":"application/json"};
async function request(path,options={}){const prefix=path==="/progress"?"/api/v1/student":"/api/v1/student/v1";const r=await fetch(`${prefix}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});if(!r.ok)throw Error(r.status===401?"نشست احراز هویت منقضی شده است":r.status===403?"دسترسی به این تکلیف مجاز نیست":r.status===404?"تکلیف در دسترس نیست":r.status===409?"مهلت ارسال تکلیف پایان یافته است":"خطا در ارتباط با سرویس");return r.json()}
function safe(v){return String(v??"—").replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function render(){const inbox=$("#inbox");inbox.innerHTML=state.items.length?state.items.map(a=>`<article class="card" tabindex="0" data-id="${a.id}"><h2>${safe(a.title)}</h2><div class="meta">کلاس ${safe(a.classroom_id)} · <span class="state">${safe(a.status)}</span></div><div class="meta">مهلت: ${safe(a.close_at||a.due_at||"تعیین نشده")}</div></article>`).join(""):"<div class='panel'>تکلیف فعالی وجود ندارد.</div>"}
async function load(){try{state.items=(await request("/assignments")).assignments||[];$("#status").textContent="آماده";$("#notice").textContent="";render()}catch(e){$("#status").textContent="خطا";$("#notice").innerHTML=`<div class="error">${safe(e.message)}</div>`}}
async function open(id){try{const d=await request(`/assignments/${id}`);state.selected=d.assignment;$("#detail").hidden=false;$("#detail").innerHTML=`<h2>${safe(d.assignment.title)}</h2><p>${safe(d.assignment.instructions)}</p><p class="meta">وضعیت: ${safe(d.assignment.status)}</p><textarea id="answer" aria-label="پاسخ تکلیف" placeholder="پاسخ خود را بنویسید…"></textarea><br><button id="submit">ثبت پاسخ</button><div id="result" aria-live="polite"></div>`;$("#submit").onclick=async()=>{const r=$("#result");try{const out=await request(`/assignments/${id}/submissions`,{method:"POST",body:JSON.stringify({content:{answer:$("#answer").value}})});r.textContent=`پاسخ ثبت شد؛ ویرایش شماره ${out.revision}`;r.className="meta"}catch(e){r.textContent=e.message;r.className="error"}}}catch(e){$("#notice").innerHTML=`<div class="error">${safe(e.message)}</div>`}}
$("#inbox").onclick=e=>{const c=e.target.closest("[data-id]");if(c)open(c.dataset.id)};$("#refresh").onclick=load;$("#progressBtn").onclick=async()=>{const p=$("#progress");p.hidden=false;p.textContent="در حال بارگذاری…";try{const d=await request("/progress");p.innerHTML=`<h2>پیشرفت من</h2><pre>${safe(JSON.stringify(d,null,2))}</pre>`}catch(e){p.innerHTML=`<div class="error">${safe(e.message)}</div>`}};$("#contentBtn").onclick=async()=>{const box=$("#content");box.hidden=false;box.textContent="در حال بارگذاری محتوای کلاس…";try{const d=await request("/v2/classroom-content");const items=d.items||[];box.innerHTML=items.length?`<h2>محتوای کلاس</h2>`+items.map(x=>`<p>${safe(x.title||x.lesson_title||"محتوای آموزشی")}</p>`).join(""):"<div class=\"empty\">محتوای منتشرشده‌ای وجود ندارد.</div>"}catch(e){box.innerHTML=`<div class=\"error\">${safe(e.message)}</div>`}};load()})();



