"""add AI usage events

Revision ID: a094e290fe6d
Revises: dcff8187f365
Create Date: 2026-09-01 21:12:02.944091
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a094e290fe6d'
down_revision: str | None = 'dcff8187f365'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('requested_tokens', sa.Integer(), nullable=False),
    sa.Column('charged_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_events_task_type'), 'ai_usage_events', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_usage_events_user_id'), 'ai_usage_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_events_user_id'), table_name='ai_usage_events')
    op.drop_index(op.f('ix_ai_usage_events_task_type'), table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    # ### end Alembic commands ###
